services:
  db:
    image: postgres
    network_mode: bridge
    container_name: db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=helpdesk
    expose:
      - 5433
    ports:
      - 5433:5432
    
  app:
    image: helpdesk
    build: .
    network_mode: bridge
    container_name: app
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/helpdesk
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    links:
      - db
volumes:
  postgres-data: